name: 'telecom_churn_databricks'
version: '1.0.0'
config-version: 2

profile: 'telecom_churn_databricks'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # You can define variables here for use across your project
  # catalog: 'workspace'
  # schema: 'telecom_churn'

models:
  telecom_churn_databricks:
    staging:
      +materialized: view
      +tags: ["staging", "telecom"]
    marts:
      +materialized: table
      +tags: ["marting", "telecom"]
      
    # Uncomment when you create marts folder
    # marts:
    #   +materialized: table
    #   +schema: marts
    #   +tags: ["mart", "production"]

tests:
  telecom_churn_databricks:
    +store_failures: true
    +schema: test_results

seeds:
  telecom_churn_databricks:
    +schema: seeds
    +tags: ["seed"]

snapshots:
  telecom_churn_databricks:
    +target_schema: snapshots
    +strategy: timestamp
    +unique_key: customer_id
